/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.windows;

/**
 *
 * @author Ксю
 */
public class Reference extends javax.swing.JFrame {

    /**
     * Creates new form Reference
     */
    public Reference() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Справка");
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Обучение:\n\tПри нажатии в главном окне кнопки «Обучение» откроется окно обучения \nсети. Прежде чем начать обучение новой сети, необходимо загрузить файл \nс обучающими данными. Это можно сделать, нажав на соответствующую кнопку \n«Загрузить файл». \n\tПосле того, как пользователь загрузит необходимый файл, он может \nизменить параметры обучения сети, заданные по умолчанию. Задать нужные \nзначения параметров можно непосредственным вводом с клавиатуры, нажав кнопку \n«Параметры».\n\tЧтобы приступить к обучению сети, следует нажать на кнопку \n«Начать обучение».Информация о ходе работы системы и об окончании обучения \nотобразится в окне в верхней части главной формы.\n\tПри желании пользователь может сохранить обученную сеть, нажав на \nкнопку «Сохранить сеть». Файл с сохраненной сетью создается автоматически в \nпапке проекта.\n\nТестирование:\n\tПри нажатии в главном меню кнопки «Тестирование» откроется окно \nтестирования сети. \n\tПеред началом тестирования, пользователь должен загрузить файл с\nтестирующими данными. Для этого он должен нажать на соответствующую кнопку \n«Загрузить файл». \n\tКроме того, пользователь может проводить тестирование, как текущей \nсети, так и любой другой сохранённой ранее. Выбор сети осуществляется \nкнопкой «Загрузить сеть».\n\tЗапуск процесса тестирования осуществляется нажатием кнопки \n«Начать тестирование». Информация о ходе процесса будет отображаться в окне \nэтой же формы.\n\tПо завершении тестирования файл с результатами прогнозирования \nсохраняется в папке проекта в формате .xlsx. \n");
        jTextArea1.setSelectionColor(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Закрыть");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
